flyway.url=jdbc:mysql://localhost:3307/blog?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
flyway.user=root
flyway.password=secretpswd
flyway.group=true
flyway.locations=filesystem:src/main/resources/db/migration